version: "3.3"

networks:
  elasticsearch:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_WEB}

services:

  elasticsearch:
    restart: always
    build: ./images/elasticsearch
    ports:
      - ${PORT_ELASTICSEARCH1}:9200
      - ${PORT_ELASTICSEARCH2}:9300
    environment:
      - cluster.name=hunzsig_cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      elasticsearch:
        ipv4_address: ${NETWORK_ELASTICSEARCH}

  kibana:
    build: ./images/kibana
    ports:
      - ${PORT_KIBANA}:5601
    depends_on:
      - elasticsearch
    networks:
      elasticsearch:
        ipv4_address: ${NETWORK_KIBANA}

  apm-server:
    build: ./images/apm-server
    ports:
      - ${PORT_APM_SERVER}:8200
    depends_on:
      - elasticsearch
      - kibana
    networks:
      elasticsearch:
        ipv4_address: ${NETWORK_APM_SERVER}